version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  withdrawals:
    container_name: withdrawals-app
    image: withdrawals
    depends_on:
      - rabbitmq
    build: .
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge

